services:
  mysql:
    image: mysql:8.0
    container_name: caltrack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: caltrack_root
      MYSQL_DATABASE: caltrack
      MYSQL_USER: caltrack
      MYSQL_PASSWORD: caltrack_pass
    ports:
      - "3306:3306"
    volumes:
      - caltrack-mysql-data:/var/lib/mysql

volumes:
  caltrack-mysql-data:
